### ISSUE TITLE
Competition promotion

### ISSUE THREAD

**Issue by dharabor** [MAPF-Competition/web_resource#16]
Discussion on specific initiatives relating to this topic is moved to: https://docs.google.com/document/d/1VK5cQqkfmzHmBoqWOYKV7PEiQpImkFes-zTgNrKdCms/edit

- We need to send call for participation to mailing lists
- Ask others in the community to link to the webpage (e.g., mapf.info)
- Promotion from Monash (FIT announcements, social media)
- Promotion from USC (Viterbi newsletter, CS department newsletter?) 
- Promotion from Rutgers and MIT (email Cathy and JJ)
- Promotion from Amazon Robotics
- Promotion from CMU 
- Other organisations (AI4Opt, Optima, MovingAI, GPPC, Flatland Discord?)

**Comment by dharabor** [comment]
We also need local promotion at each instiution (flyers etc)

**Comment by nobodyczcz** [comment]
**Online Communities:**

Reddit
- r/ReinforcementLearning 
- r/machinelearning
- r/deeplearning
- r/gamedev

Contents:
- Text for each community
- including who we are
- why the competition is interested in the target community

Social media:

- Twitter/X

**Comment by dharabor** [comment]
We should promote at upcoming conferences:

- IJCAI-2023
- AIIDE-2023 (@dharabor chase up with Vadim)

**Comment by nobodyczcz** [comment]
twitter account for competition

**Comment by optmly** [comment]
What is the status regarding this? I haven't seen an announcement on robotics-worldwide. I have done some advertising in China. What am I responsible for? Let me know how I can help without making duplicate efforts.

**Comment by nobodyczcz** [comment]
Moved to google drive
