### ISSUE TITLE
FAQ: Multiple Collaborators 

### ISSUE THREAD

**Issue by nobodyczcz** [MAPF-Competition/web_resource#18]
Give suggestions on how to work in a shared git repo with multiple collaborators:

- System only allows a single submitter.
- To work with a team of people on a shared git repo, you can create a separate team repo and add team members there, and link the repo with your local repo through git remote.
- When it is time to submit, you can add your competition repo as a new remote, and the nominated submitter can push the changes.

**Comment by YueZhang-studyuse** [comment]
Commit in develop branch (42b05d3ca9af00d24d93ef15a9aeda303c931449). Add the Q and answer according to the provided text.

**Comment by dharabor** [comment]
Looks like this has been merged into master. Closing.
