### ISSUE TITLE
Visulisations are broken

### ISSUE THREAD

**Issue by dharabor** [MAPF-Competition/web_resource#5]
Pressing SOC, Makespan etc buttons does not produce a plot.

**Comment by dharabor** [comment]
Well, the new version is improved, but the fast mover button is still broken, and we have no button for line honours?

**Comment by dharabor** [comment]
It seems possible to generate two lines with the same colour. This also needs to be fixed.

**Comment by dharabor** [comment]
The virtual best is not indicated anywhere either. I think this is useful context.

**Comment by nobodyczcz** [comment]
> The virtual best is not indicated anywhere either. I think this is useful context.

Yes, I realized this as well. Working on showing the current virtual best. This also means, we many want plots on each problem instance showing people's achivements on tasks finished.

**Comment by nobodyczcz** [comment]
> Well, the new version is improved, but the fast mover button is still broken, and we have no button for line honours?

I realized the line honours visualisation is more tricky than others, thinking about how to plot this thing better.
The fast mover is not broken, it's empty because we don't have time to create a valid fast mover implementation yet. Thus no submission valid for fast mover.
