### ISSUE TITLE
Trend line colours

### ISSUE THREAD

**Issue by dharabor** [MAPF-Competition/web_resource#7]
The colours used for different solvers seems to be generated randomly and changes when pressing a button (e.g., SOC) and then another button (e.g., Score). Colours should be retained while exploring the data.

**Comment by dharabor** [comment]
It seems possible to generate two lines with the same colour. This also needs to be fixed.

**Comment by GreatenAnoymous** [comment]
Previously, the colors of the lines in the chart were randomly generated. Now, the colors of the lines are generated in a fixed manner.
