### ISSUE TITLE
Warehouse animation

### ISSUE THREAD

**Issue by dharabor** [MAPF-Competition/web_resource#8]
The layout of picking stations in our MAPF animation is not the same as the example warehouse. There is not enough space between the endpoint locations (should be two empty columns/rows). 

Also, it would be nice to:
(a) further increase the number of agents (+20)
(b) remove the start locations and any non-assigned goal locations.

**Comment by dharabor** [comment]
I see the update animation is available in the visualiser repo. Please upload to the web_resources repo and update the file ``problem.md``

**Comment by dharabor** [comment]
Yue, maybe you can have a go at this one please?

**Comment by nobodyczcz** [comment]
Oh, Shao-Hung already send us the updated video. I have updated the one in the web-resource as well.
