### ISSUE TITLE
Remove redundant whitespace from content pane

### ISSUE THREAD

**Issue by dharabor** [MAPF-Competition/web_resource#9]
The "resources" content pane has extra whitespace padding after the end of the text. It's not an issue on other pages, so I assume it's part of the source html. Maybe some redundant divs? We should remove it. The page looks ugly with a long tail of empty whitespace.

**Comment by dharabor** [comment]
FAQ page suffers a similar problem. Also Organisers page, Rules page, Leaderboard

**Comment by nobodyczcz** [comment]
I removed the extra space. But the result is that the pane size changes before and after pane contents are changed.
